DefaultContentLanguage = "en"
author = "Stephen Ajulu"
baseURL = "https://relaxed-einstein-109b20.netlify.com/"
copyright = "Copyright © 2008–2019, Stephen Ajulu; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Ajulu's Thoughts"
[[menu.main]]
identifier = "author"
name = "Author"
url = "https://stephenajulu.com"
weight = 3
[[menu.main]]
identifier = "image-credit"
name = "Image Credit"
url = "/image-credit/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[params]
description = "Tech, Cybersecurity, Personal Dev and More"
facebook = "https://facebook.com/stephenajulu"
github = "https://github.com/stephenajulu"
mainSections = ["post"]
twitter = "https://twitter.com/stephenajulu"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
